info:
  component: Api Gateway Service

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    ROOT: INFO
    org.springframework.web: WARNING

apigateway:
  inventory:
    url: http://127.0.0.1:48080
shell.ssh.port: 48022